apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'infnet-guia-app'
        metrics_path: '/api/metrics'
        static_configs:
          - targets: ['infnet-guia-service:3000']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']