apiVersion: v1
kind: Service
metadata:
  name: infnet-guia-service
  namespace: application
spec:
  selector:
    app: infnet-guia-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer