name: Docker Image CI/CD

on:
  push:
    branches:
      - main # Substitua pela branch que deseja monitorar

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t gustavogdm/infnet-guia-app:latest .

      # Push da imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push gustavogdm/infnet-guia-app:latest
